#!/usr/bin/ruby -w

# Loads 'lib/' to the $LOAD_PATH
libdir = File.dirname(__FILE__) + '/lib/'
$LOAD_PATH.unshift(libdir) unless $LOAD_PATH.include?(libdir)

require "console/console"

begin
  io = ConsoleIO.new
  console = Console.new(io)
  console.play
rescue Interrupt => e
  puts "\n\nExiting the game..."
end